export const state = () => ({
  que: [
    { code:true, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[""], Q_img:"",   img:"",   this_ans:[ 2, 3 ],   ques:"NATの説明として正しいものを2つ選択してください ルータはNATテーブルを持ち、そこに変換元、変換後のアドレスが登録される。 ",   ans:[     { value:'a', text: "LAN内で用いられるグローバルIPアドレスを変換する", },     { value:'b', text: "スタティックNATでは1つのグローバルIPアドレスを複数のプライベートIPアドレスで共有することができる。", },     { value:'c', text: "LANとインターネットの境界にあたるルータで、プライベートIPアドレスをグローバルIPアドレスに変換する。", },     { value:'d', text: "ルータはNATテーブルを持ち、そこに変換元、変換後のアドレスが登録される。", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 1 ],   ques:"次の文章の中から正しいものを1つ選択してください ",   ans:[     { value:'a', text: "一方向NATは、外部ネットワークから通信を開始することができるNATである。", },     { value:'b', text: "一方向NATは。外部ネットワークから通信を開始することができないNATである。", },     { value:'c', text: "双方向NATは、外部ネットワークから通信を開始して内部と通信することができないNATである", },     { value:'d', text: "双方向NATは、一般的なインターネット接続で使用されるNATである。", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 2 ],   ques:"次の[ ① ]に当てはまる用語を選択してください。一つの内部グローバルアドレスに対して、複数の内部グローバルアドレスを割り当てるため　[ ① ]も変換します。また、NAPTの場合は内部から通信が発生して初めてNATテーブルに情報が登録されるため、[ ]となります。 ",   ans:[     { value:'a', text: "プロトコル番号", },     { value:'b', text: "シーケンス番号", },     { value:'c', text: "ポート番号", },     { value:'d', text: "双方向NAT", },     { value:'e', text: "一方向NAT", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 4 ],   ques:"次の[ ② ]に当てはまる用語を選択してください。一つの内部グローバルアドレスに対して、複数の内部グローバルアドレスを割り当てるため　[ ]も変換します。また、NAPTの場合は内部から通信が発生して初めてNATテーブルに情報が登録されるため、[ ② ]となります。 ",   ans:[     { value:'a', text: "プロトコル番号", },     { value:'b', text: "シーケンス番号", },     { value:'c', text: "ポート番号", },     { value:'d', text: "双方向NAT", },     { value:'e', text: "一方向NAT", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 4 ],   ques:"ダイナミックNATで用いるアドレスプールを設定するコマンドとして正しいものを1つ選択してください。 ",   ans:[     { value:'a', text: "(config)#ip nat inside source static 192.168.1.1", },     { value:'b', text: "(config)#ip nat poo test_pool 192.168.1.0 netmask 255.255.255.0", },     { value:'c', text: "(config)#access-lists 1permit 192.168.1.0 0.0.0.255", },     { value:'d', text: "(config)#ip nat inside source list 1 pool test_pool", },     { value:'e', text: "(config)#ip nat pool test_pool 192.168.1.1 192.168.1.5 netmask 255.255.255.0", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 0 ],   ques:"NATテーブル上に登録されたエントリをすべて削除するコマンドを1つ選択してください。 ",   ans:[     { value:'a', text: "#clear ip nat translation *", },     { value:'b', text: "(config)#clear ip nat translation * ", },     { value:'c', text: "(config)#no ip nat inside source static 192.168.1.1 172.16.1.1", },     { value:'d', text: "#show ip nat taranslations", },     { value:'e', text: "#show ip nat statistics", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 2 ],   ques:"次の文章の中から、正しいものを１つ選択してください。 ",   ans:[     { value:'a', text: "ダイナミックNATではACLでdenyに該当sるIPアドレスが変換対象になる", },     { value:'b', text: "NATコンフィギュレーションモードでアドレスプールを作成する必要がある。", },     { value:'c', text: "変換に使用される内部ローカルアドレスを、ACLで指定する", },     { value:'d', text: "ACLとアドレスプールは自動的に紐づけられる", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 3 ],   ques:"NATテーブルを確認するコマンドを１つ選択してください。 ",   ans:[     { value:'a', text: "#show ip nat inside source", },     { value:'b', text: "#show ip nat", },     { value:'c', text: "#show nat trancelations", },     { value:'d', text: "#show ip nat translations", },     { value:'e', text: "#show ip nat stations", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 1 ],   ques:"NAT変換の統計情報を確認するコマンドを１つ選択してください。 ",   ans:[     { value:'a', text: "#show ip nat overload", },     { value:'b', text: "#show ip nat statistics", },     { value:'c', text: "#show running-config", },     { value:'d', text: "#show ip nat translations", },  ] },
    { code:true, codes:[ "Pro Inside global   Inside local   Outside local   Outside global", "--- 100.0.0.1       192.168.100.1      ---" ], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 2, 3 ],   ques:"ルータ上でNAT設定を行い、実際に通信を開始する前に変換テーブルを確認したところ、次のような結果が得られました。この時のNATの動作及びルータ上に設定したコマンドについて、正しいものを2つ選択してください。 ",   ans:[     { value:'a', text: "ダイナミックNATの設定により作成された変換テーブルである。", },     { value:'b', text: "すべての通信はすべてグローバルIPアドレス100.0.0.1に変換されて送信される", },     { value:'c', text: "NATの変換テーブルがあらかじめ作成されており、常に１対１の変換が行われる", },     { value:'d', text: "(config)#ip nat inside source static 192.168.100.1 100.0.0.1コマンドを実行している", },     { value:'e', text: "(config)#ip nat inside source 192.168.100.1 100.0.0.1 コマンドを実行している", },     { value:'f', text: "(config)#ip nat outside source static 100.0.0.1 192.168.100.1コマンドを実行している", },     { value:'g', text: "(config)#ip nat outside source 100.0.0.1 192.168.100.1コマンドを実行している。", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 3 ],   ques:"(config)#ip nat inside source list 90 interface Ethernet 0/0 overloadコマンドを実行したときの動作として正しく述べられているものを１つ選択してください。 ",   ans:[     { value:'a', text: "アクセスリストinsideに一致したアドレスはEthernet0/0インターフェイルのIPアドレスに変換される", },     { value:'b', text: "アクセスリストinsideに一致したアドレスはEthernet0/0ネットワークのIPアドレスに変換される。", },     { value:'c', text: "Ethernet0/0側のLAN内のホストあくセスリスト90でプールされたアドレスに変換される", },     { value:'d', text: "アクセスリスト90に一致したアドレスがPATによってE0/0もしくはEthernet0/0インターフェイスのIPアドレスに変換される", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 3 ],   ques:"DHCPに関する説明として、正しいものを一つ選択してください ",   ans:[     { value:'a', text: "DHCPは、ドメイン名からIPドレスを解決する仕組みを提供するプロトコルである。", },     { value:'b', text: "DHCPは、宛先ホストとの疎通確認の際に使用されるプロトコルである", },     { value:'c', text: "DHCPは、インターネット接続の際にIPアドレスを変換するためのプロトコルである。", },     { value:'d', text: "DHCPは、ネットワークをリ位要するために必要となる情報を自動的に割り当てるためのプロトコルである。", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 0, 2, 3 ],   ques:"DHCPサーバがクライアントに配布する情報を３つ選択してください ",   ans:[     { value:'a', text: "DNSサーバのIPアドレス", },     { value:'b', text: "現在時刻", },     { value:'c', text: "クライアントに割り当てるIPアドレスとサブネットマスク", },     { value:'d', text: "デフォルトゲートウェイのIPアドレス", },     { value:'e', text: "ルーティングの情報", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 0, 1 ],   ques:"ルータをDHCPサーバとして設定する際、必ず設定しなければいけない項目を２つ選択してください ",   ans:[     { value:'a', text: "配布するIPアドレスのネットワークとサブネットマスクの指定", },     { value:'b', text: "アドレスプールの作成", },     { value:'c', text: "リース期間の指定", },     { value:'d', text: "DNSサーバの指定", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 1 ],   ques:"ルータのインターフェイスに、DHCPでIPアドレスを設定するコマンドを1つ選択してください ",   ans:[     { value:'a', text: "(config)#ip dhcp pool test", },     { value:'b', text: "(config-if)#ip address dhcp", },     { value:'c', text: "(config-if)#ip address auto", },     { value:'d', text: "(config-if)#ip address enable", },     { value:'e', text: "(config-if)#ip helper-address 192.168.1.254", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 2 ],   ques:"192.168.1.1 ~ 192.168.1.10をDHCPクライアントに配布するIPアドレスから除外するコマンドを１つ選択してください ",   ans:[     { value:'a', text: "(dhcp-config)#network 192.168.1.0 255.255.255.0", },     { value:'b', text: "(config)#ip dhcp pool ccna", },     { value:'c', text: "(config)#ip dhcp excluded-address 192.168.1.1 192.168.1.10", },     { value:'d', text: "(config-if)#ip helper-address 192.168.1.1", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 1 ],   ques:"DHCPで割り当てたIPアドレスと、配布先のMACアドレスなどを確認できるコマンドを１つ選択してください。 ",   ans:[     { value:'a', text: "#show ip dhcp conflict", },     { value:'b', text: "#show ip dhcp binding", },     { value:'c', text: "#show ip dhcp pool", },     { value:'d', text: "#show running-config", },     { value:'e', text: "#show mac-address-table", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 2 ],   ques:"Gratuitos ARPの目的を一つ選択してください ",   ans:[     { value:'a', text: "通信相手のIPアドレスとそれに紐づくMACアドレスを解決する", },     { value:'b', text: "DHCPサーバを発見する", },     { value:'c', text: "割り当てられたIPアドレスがすでにほかのホストに割り当てられていないかを確認する", },     { value:'d', text: "通史泣いてのIPアドレスを確認する", },     { value:'e', text: "DHCPサーバーのMACアドレスを解決する", },  ] },
    { code:false, codes:[], acode:true, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "1世紀は馬鹿。", ], Q_img:"",   img:"",   this_ans:[ 1 ],   ques:"CiscoルータをDHCPサーバとした場合、DHCPによるIPアドレスなどの割り当てリース期間のデフォルトの値として、適切なものを1つ選択してください ",   ans:[     { value:'a', text: "12時間", },     { value:'b', text: "1日", },     { value:'c', text: "1週間", },     { value:'d', text: "1か月", },     { value:'e', text: "1年", },     { value:'f', text: "1世紀", },  ] },
    { code:false, codes:[], acode:false, acodes:[], user_ans:[], icon:"", reveal:false, Explanation:[ "", ], Q_img:"",   img:"",   this_ans:[ 1, 4 ],   ques:"DHCPの動作についての説明で、正しいものを2つ選択してください ",   ans:[     { value:'a', text: "DHCPクライアントは、IPアドレスのコンフリクトを検出するためにTCPやRARPを使用する", },     { value:'b', text: "IPアドレスのコンフリクトが検出された場合、IPアドレスを再度クライアントに配布されるようにするには、管理者が手動でコマンドを実行する必要がある", },     { value:'c', text: "IPアドレスのコンフリクトが検出された場合、IPアドレスは管理差が設定した時間だけプールから削除される", },     { value:'d', text: "IPアドレスのコンフリクトが検出された場合、そのIPアドレスはルータを初期化するまで配布されない", },     { value:'e', text: "DHCPではIPアドレスのコンフリクトを検出するためにpingやGratutous ARPを使用する。", },  ] },

  ]
})
